---
abstract: 'Provides a function keyword'
author:
  - "Robert 'phaylon' Sedlacek <rs@474.at>"
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101900, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Syntax-Feature-Function
requires:
  B::Hooks::EndOfScope: 0.08
  Carp: 0
  Function::Parameters: 0.04
  Test::More: 0.94
  namespace::clean: 0.14
  syntax: 0
resources:
  repository: http://github.com/phaylon/Syntax-Feature-Function
version: 0.001
