---
abstract: 'Provides a function keyword'
author:
  - "Robert 'phaylon' Sedlacek <rs@474.at>"
build_requires:
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300021, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Syntax-Feature-Function
requires:
  B::Hooks::EndOfScope: 0.08
  Carp: 0
  Function::Parameters: 0.04
  Import::Into: 1.001000
  namespace::clean: 0.14
  syntax: 0.001
resources:
  repository: git://github.com/phaylon/Syntax-Feature-Function.git
version: 0.002
